server:
  port: 8088
spring:
  application:
    name: client1-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka  
  instance:
    prefer-ip-address: true 
